### ISSUE TITLE
AnimationHasEnded does not exist

### ISSUE THREAD

**Issue by rocuh** [dazinator/BlazorDeferredRemove#1]
H,i thanks for this component! Had a small issue with the RemoveOnCssAnimationEnd component, in that the javascript example says to call AnimationHasEnded

```
var onAnimationEnded = function (args) {
                var name = args.animationName;
                dotnetHelper.invokeMethodAsync('AnimationHasEnded', name);
            };
```
but the code only seems to expect TransitionHasEnded even for animations. It does work ok if you change the javascript to invoke 'TransitionHasEnded' for animations as well.

**Comment by dazinator** [comment]
Hi. Glad this has helped- and thanks for letting me know, I'll update the script at some point in the future and will leave this open until then (pr's also welcome).

**Comment by dazinator** [comment]
I have fixed this, and also updated the readme to show including the javascript file from the package.

**Comment by cr00ksie** [comment]
I think this might have become a problem again since removing the Animation Helper. As said above it does work ok if you change the javascript to invoke 'TransitionHasEnded' for animations. Maybe the TransitionHelper and TransitionCompleteHelper could be renamed to something more generic for both animation and transitions too?

**Comment by dazinator** [comment]
@cr00ksie 
Thanks for reporting. I have only used this component for transitions so far, animations "should" work but there are no tests and not even an example in the sample of an animation- so this tends to get missed and so I am tempted to believe you that there could be a problem there. If you feel like contributing, I'd be open to a PR that extends the sample to have an animation - which can then be used as a repro? From there if the changes you propose will fix that sample I'd be open to those as well.
